version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: qartjackie/foodgram-backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
  frontend:
    env_file: .env
    image: qartjackie/foodgram-frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: qartjackie/foodgram-nginx
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
