"""Настройки текстовых полей моделей foodgram."""


TAG_NAME_LENGTH = 200
TAG_COLOR_NAME_LENGTH = 16
INGREDIENT_NAME_LENGTH = 200
INGREDIENT_MEASUREMENT_UNIT_LENGTH = 200
RECIPE_NAME_LENGTH = 200
RECIPE_TEXT_LENGTH = 200
USER_USERNAME_LENGTH = 150
USER_EMAIL_LENGTH = 254
USER_FIRST_NAME_LENGTH = 150
USER_LAST_NAME_LENGTH = 150
